version: "3.9"

x-params:
  &default-params
  image: ghcr.io/giongto35/cloud-game/cloud-game:${IMAGE_TAG:-dev}
  network_mode: "host"
  privileged: true
  restart: always
  logging:
    driver: "journald"

services:

  coordinator:
    <<: *default-params
    command: coordinator
    volumes:
      - ${APP_DIR:-/cloud-game}/cache:/usr/local/share/cloud-game/assets/cache
      - ${APP_DIR:-/cloud-game}/games:/usr/local/share/cloud-game/assets/games
      - ${APP_DIR:-/cloud-game}/home:/root/.cr

  worker:
    <<: *default-params
    depends_on:
      - coordinator
    deploy:
      mode: replicated
      replicas: 4
    environment:
      - MESA_GL_VERSION_OVERRIDE=3.3
    #entrypoint: [ "/bin/sh", "-c", "xvfb-run -a $$@", "" ]
    command: worker
    volumes:
      - ${APP_DIR:-/cloud-game}/cache:/usr/local/share/cloud-game/assets/cache
      - ${APP_DIR:-/cloud-game}/cores:/usr/local/share/cloud-game/assets/cores
      - ${APP_DIR:-/cloud-game}/games:/usr/local/share/cloud-game/assets/games
      - ${APP_DIR:-/cloud-game}/libretro:/usr/local/share/cloud-game/libretro
      - ${APP_DIR:-/cloud-game}/home:/root/.cr
