version: 4

coordinator:
  debug: true
  server:
    address:
    https: true
    tls:
      domain: cloudretro.io
  analytics:
    inject: true
    gtag: UA-145078282-1

worker:
  debug: true
  network:
    coordinatorAddress: cloudretro.io
    publicAddress: cloudretro.io
    secure: true
  server:
    https: true
    tls:
      address: :444
      domain: cloudretro.io

emulator:
  threads: 4
  libretro:
    logLevel: 1
    cores:
      list:
        mame:
          options:
            fbneo-cpu-speed-adjust: 200%
        pcsx:
          altRepo: true
